### ISSUE TITLE
I answer a question, then it says ''No'' and proceeds without clarifying anything else + Hallucinating

### ISSUE THREAD

**Issue by zdondada** [AntonOsika/gpt-engineer#37]
This keeps happening...

PS C:\Users\jews4\OneDrive\one2\OneDrive\Documents\gpt-engineer-main> python main.py gpt-zdondada-builds
Areas that need clarification:
1. Login/Register screen design and layout
2. Main Search For Prescribers screen design and layout
3. Account/Credits screen design and layout
4. Contact Us screen design and layout
5. App Bar design and functionality
6. Field mapping for search results and More Info modal
7. User registration process and required information
8. Credits purchase process and options

Clarifying question:
For the main Search For Prescribers screen, how should the search results be displayed? Should they be in a table format or a card layout?
(answer in text, or "q" to move on)
table

No
Core classes, functions, and methods:

1. App.vue - Main Vue application component
2. router/index.js - Vue Router configuration
3. store/index.js - Vuex store configuration
4. components/LoginRegister.vue - Login/Register component

Aborted!
5. components/SearchPrescribers

ALSO, if I let it run through the project, it outputs a couple of things and then tells me the rest of the files are in a non-existent GitHub

**Comment by zdondada** [comment]
This was in the logs if it helps:

 {"role": "assistant", "content": "Areas that need clarification:\n1. Login/Register screen design and layout\n2. Main Search For Prescribers screen design and layout\n3. Account/Credits screen design and layout\n4. Contact Us screen design and layout\n5. App Bar design and functionality\n6. Field mapping for search results and More Info modal\n7. User registration process and required information\n8. Credits purchase process and options\n\nClarifying question:\nFor the main Search For Prescribers screen, how should the search results be displayed? Should they be in a table format or a card layout?"}, {"role": "user", "content": "table\n\nIs anything else unclear? If yes, only answer in the form:\n{remaining unclear areas} remaining questions.\n{Next question}\nIf everything is sufficiently clear, only answer \"no\"."}, {"role": "assistant", "content": "No"}]

**Comment by UrbanLegendXV** [comment]
I'm getting this too. It might be a token limiter?

**Comment by UrbanLegendXV** [comment]
Whenever and I paste it gives a NO

I was giving typed replies and got four questions in before getting a NO

**Comment by zdondada** [comment]
Tried again, same thing, here's another example of the hallucinating

Please find the code for the components and API functions in the following files:

1. [Login.vue](https://gist.github.com/assistant-dev/7c4e5d6e5d6a6e0e7a3e7a0b7e4b5d5e)
2. [MainSearch.vue](https://gist.github.com/assistant-dev/4e9f3e8d8e1a6a6e0e7a3e7a0b7e4b5d5e)
3. [Account.vue](https://gist.github.com/assistant-dev/7c4e5d6e5d6a6e0e7a3e7a0b7e4b5d5e)
4. [Contact.vue](https://gist.github.com/assistant-dev/7c4e5d6e5d6a6e0e7a3e7a0b7e4b5d5e)
5. [AppBar.vue](https://gist.github.com/assistant-dev/7c4e5d6e5d6a6e0e7a3e7a0b7e4b5d5e)
6. [api.js](https://gist.github.com/assistant-dev/7c4e5d6e5d6a6e0e7a3e7a0b7e4b5d5e)
7. [utils.js](https://gist.github.com/assistant-dev/7c4e5d6e5d6a6e0e7a3e7a0b7e4b5d5e)

**Comment by UrbanLegendXV** [comment]
I think this concept needs some tiered agent creation to solve intermediate tasks

**Comment by ScorchChamp** [comment]
Fixed in https://github.com/AntonOsika/gpt-engineer/pull/21

**Comment by majorrawdawg** [comment]
I'm also getting this issue, where it simply replies "no" and then it packs up it's stuff and goes home (it just terminates with no errors and ceases to do anymore development/building...sometimes it gets through only one of its clarification questions, sometimes multiple...but it always seems to happen before it gets answers to them all.

**Comment by RadientBrain** [comment]
still getting a "no" after clarifying it the task and just runs without reclarification of other tasks

**Comment by itssonkab** [comment]
I am having the same issues.

**Comment by patillacode** [comment]
I think this was just fixed in [6a3f7eb](https://github.com/AntonOsika/gpt-engineer/commit/6a3f7eb9de07922c6b2bc2b18e194bdeae2d158f)
